<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>D2Packets</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net20</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="D2Data">
      <HintPath>../../AGB.MapHack release/D2Data.dll</HintPath>
    </Reference>
    <Reference Include="ETUtils" />
  </ItemGroup>
</Project>